name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - azure-app-service-deployment
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Python dependencies
        run: |
          uv sync
          
      - name: Export requirements.txt for Azure
        run: |
          uv export --no-hashes --no-editable --format requirements-txt | grep -v "^\." > requirements.txt
          echo "Generated requirements.txt:"
          head -20 requirements.txt

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build
          echo "Frontend build completed"
          ls -la dist || echo "dist directory not found!"
          cd ..

      - name: Create deployment package
        run: |
          # For Azure App Service ZIP deploy - files must be at root of ZIP, not in a subdirectory
          # Copy everything to a temporary location, then zip from there
          
          # Create temp directory
          mkdir -p .deploy_temp
          
          # Copy backend source
          cp -r backend .deploy_temp/
          
          # Copy frontend build
          if [ -d "frontend/dist" ]; then
            mkdir -p .deploy_temp/frontend
            cp -r frontend/dist .deploy_temp/frontend/dist
            echo "Frontend dist copied"
          else
            echo "Warning: frontend/dist not found"
          fi
          
          # Copy Python requirements (Oryx will use this)
          cp requirements.txt .deploy_temp/
          
          # Copy placeholder instructions.md (will be replaced by admin interface)
          # This allows the app to start without the full instructions
          cp instructions_placeholder.md .deploy_temp/instructions.md
          
          # Copy startup script to root (where Oryx expects it)
          cp startup.sh .deploy_temp/
          
          # List what we're deploying
          echo "Deployment package contents:"
          ls -la .deploy_temp/
          
          # Create ZIP from inside the temp directory (so files are at root of ZIP)
          cd .deploy_temp
          zip -r ../deploy.zip .
          cd ..
          
          echo "ZIP file created:"
          ls -lh deploy.zip

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Debug - List downloaded files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'intunediagnostics'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy.zip
